# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoldCoinsTelaSMS.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GoldCoinsTelaConfirmacao import Ui_TelaConfirmacao

class Ui_TelaSMS(object):
    def OpenConfirmWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TelaConfirmacao()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, TelaSMS):
        TelaSMS.setObjectName("TelaSMS")
        TelaSMS.resize(1005, 840)
        self.centralwidget = QtWidgets.QWidget(TelaSMS)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setStyleSheet("background-color: #fff;")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.verticalLayout.addWidget(self.top)
        self.containerlogo = QtWidgets.QFrame(self.centralwidget)
        self.containerlogo.setMaximumSize(QtCore.QSize(16777215, 80))
        self.containerlogo.setStyleSheet("background-color: #fff;")
        self.containerlogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.containerlogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerlogo.setObjectName("containerlogo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.containerlogo)
        self.verticalLayout_2.setContentsMargins(30, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_3 = QtWidgets.QFrame(self.containerlogo)
        self.logo_3.setMaximumSize(QtCore.QSize(281, 61))
        self.logo_3.setStyleSheet("background-image: url(:/Logo/Icone GoldCoins pqn.png);\n"
" background-repeat: norepeat;")
        self.logo_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_3.setObjectName("logo_3")
        self.verticalLayout_2.addWidget(self.logo_3)
        self.verticalLayout.addWidget(self.containerlogo)
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.container.setStyleSheet("background-color: #fff;")
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container_3 = QtWidgets.QFrame(self.container)
        self.container_3.setMaximumSize(QtCore.QSize(1000, 1200))
        self.container_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.container_3.setStyleSheet("background-color: #fff;")
        self.container_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_3.setObjectName("container_3")
        self.label_4 = QtWidgets.QLabel(self.container_3)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 531, 61))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(251, 190, 119);\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.BotaoVoltar = QtWidgets.QPushButton(self.container_3)
        self.BotaoVoltar.setGeometry(QtCore.QRect(140, 580, 101, 51))
        self.BotaoVoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoVoltar.setStyleSheet("QPushButton {\n"
"    color: #81BAFD;\n"
"    background-color: #fff;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #81BAFD;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #738FF0;\n"
"    border: 2px solid#738FF0;\n"
"}\n"
"")
        self.BotaoVoltar.setObjectName("BotaoVoltar")
        self.frame = QtWidgets.QFrame(self.container_3)
        self.frame.setGeometry(QtCore.QRect(20, 70, 961, 20))
        self.frame.setStyleSheet("background-image: url(:/Line/Line.png);\n"
"background-repeat: norepeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BotaoProsseguir = QtWidgets.QPushButton(self.container_3, clicked = lambda: self.OpenConfirmWindow())
        self.BotaoProsseguir.setGeometry(QtCore.QRect(690, 580, 141, 51))
        self.BotaoProsseguir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoProsseguir.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #81BAFD;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #738FF0;\n"
"}\n"
"")
        self.BotaoProsseguir.setObjectName("BotaoProsseguir")
        self.label_8 = QtWidgets.QLabel(self.container_3)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 291, 41))
        self.label_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(251, 190, 119);")
        self.label_8.setObjectName("label_8")
        self.check_dolar = QtWidgets.QCheckBox(self.container_3)
        self.check_dolar.setGeometry(QtCore.QRect(60, 160, 121, 31))
        self.check_dolar.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"")
        self.check_dolar.setObjectName("check_dolar")
        self.check_euro = QtWidgets.QCheckBox(self.container_3)
        self.check_euro.setGeometry(QtCore.QRect(60, 210, 121, 31))
        self.check_euro.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"\n"
"")
        self.check_euro.setObjectName("check_euro")
        self.check_bitcoin = QtWidgets.QCheckBox(self.container_3)
        self.check_bitcoin.setGeometry(QtCore.QRect(60, 260, 121, 31))
        self.check_bitcoin.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"\n"
"")
        self.check_bitcoin.setObjectName("check_bitcoin")
        self.label_9 = QtWidgets.QLabel(self.container_3)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 611, 41))
        self.label_9.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(251, 190, 119);")
        self.label_9.setObjectName("label_9")
        self.escolha_finaldia = QtWidgets.QRadioButton(self.container_3)
        self.escolha_finaldia.setGeometry(QtCore.QRect(60, 410, 231, 31))
        self.escolha_finaldia.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"")
        self.escolha_finaldia.setObjectName("escolha_finaldia")
        self.escolha_sexta = QtWidgets.QRadioButton(self.container_3)
        self.escolha_sexta.setGeometry(QtCore.QRect(60, 460, 231, 31))
        self.escolha_sexta.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"")
        self.escolha_sexta.setObjectName("escolha_sexta")
        self.horizontalLayout_2.addWidget(self.container_3)
        self.verticalLayout.addWidget(self.container)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bottom.setStyleSheet("background-color: #fff;")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.label_5 = QtWidgets.QLabel(self.bottom)
        self.label_5.setGeometry(QtCore.QRect(820, 10, 178, 18))
        self.label_5.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(251, 190, 119);\n"
"font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.bottom)
        TelaSMS.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaSMS)
        self.BotaoVoltar.clicked.connect(TelaSMS.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TelaSMS)

    def retranslateUi(self, TelaSMS):
        _translate = QtCore.QCoreApplication.translate
        TelaSMS.setWindowTitle(_translate("TelaSMS", "MainWindow"))
        self.label_4.setText(_translate("TelaSMS", "Hora de personalizar suas notificações!"))
        self.BotaoVoltar.setText(_translate("TelaSMS", "Voltar"))
        self.BotaoProsseguir.setText(_translate("TelaSMS", "Prosseguir"))
        self.label_8.setText(_translate("TelaSMS", "Selecione suas moedas:"))
        self.check_dolar.setText(_translate("TelaSMS", "Dólar"))
        self.check_euro.setText(_translate("TelaSMS", "Euro"))
        self.check_bitcoin.setText(_translate("TelaSMS", "Bitcoin"))
        self.label_9.setText(_translate("TelaSMS", "Com que frequência deseja receber as mensagens?"))
        self.escolha_finaldia.setText(_translate("TelaSMS", "Ao final do dia"))
        self.escolha_sexta.setText(_translate("TelaSMS", "Apenas às sextas"))
        self.label_5.setText(_translate("TelaSMS", "2022 CopyRight © Solutech"))
#import images_rc
