# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoldCoinsTelaConfirmacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GoldCoinsTelaFinal import Ui_TelaFinal


class Ui_TelaConfirmacao(object):
    def OpenFinalWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TelaFinal()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, TelaConfirmacao):
        TelaConfirmacao.setObjectName("TelaConfirmacao")
        TelaConfirmacao.resize(1005, 750)
        self.centralwidget = QtWidgets.QWidget(TelaConfirmacao)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.verticalLayout.addWidget(self.top)
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QFrame(self.container)
        self.main.setMaximumSize(QtCore.QSize(450, 650))
        self.main.setStyleSheet("background-color: rgb(255, 255, 255); border-radius: 10px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.Logo = QtWidgets.QFrame(self.main)
        self.Logo.setGeometry(QtCore.QRect(80, 50, 290, 51))
        self.Logo.setMaximumSize(QtCore.QSize(291, 51))
        self.Logo.setStyleSheet("background-image: url(:/Logo/Icone GoldCoins pqn.png);\n"
"background-repeat: norepeat;")
        self.Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.label_4 = QtWidgets.QLabel(self.main)
        self.label_4.setGeometry(QtCore.QRect(130, 210, 181, 61))
        self.label_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(251, 190, 119);\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.main)
        self.textBrowser.setGeometry(QtCore.QRect(40, 290, 371, 111))
        self.textBrowser.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"font-weight: bold;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.BotaoConfirmar = QtWidgets.QPushButton(self.main, clicked = lambda: self.OpenFinalWindow())
        self.BotaoConfirmar.setGeometry(QtCore.QRect(40, 540, 141, 51))
        self.BotaoConfirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoConfirmar.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #81BAFD;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #738FF0;\n"
"}\n"
"")
        self.BotaoConfirmar.setObjectName("BotaoConfirmar")
        self.BotaoCancelar = QtWidgets.QPushButton(self.main)
        self.BotaoCancelar.setGeometry(QtCore.QRect(250, 540, 171, 51))
        self.BotaoCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoCancelar.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #FF9090;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E75858;\n"
"}\n"
"")
        self.BotaoCancelar.setObjectName("BotaoCancelar")
        self.horizontalLayout.addWidget(self.main)
        self.verticalLayout.addWidget(self.container)
        self.bot = QtWidgets.QFrame(self.centralwidget)
        self.bot.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bot.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.bot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bot.setObjectName("bot")
        self.label_2 = QtWidgets.QLabel(self.bot)
        self.label_2.setGeometry(QtCore.QRect(820, 10, 178, 18))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.bot)
        TelaConfirmacao.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaConfirmacao)
        self.BotaoCancelar.clicked.connect(TelaConfirmacao.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TelaConfirmacao)

    def retranslateUi(self, TelaConfirmacao):
        _translate = QtCore.QCoreApplication.translate
        TelaConfirmacao.setWindowTitle(_translate("TelaConfirmacao", "MainWindow"))
        self.label_4.setText(_translate("TelaConfirmacao", "Atenção!"))
        self.textBrowser.setHtml(_translate("TelaConfirmacao", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#483f33;\">Você confirma que deseja receber as mensagens </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#483f33;\">no número cadastrado?</span></p></body></html>"))
        self.BotaoConfirmar.setText(_translate("TelaConfirmacao", "Confirmar"))
        self.BotaoCancelar.setText(_translate("TelaConfirmacao", "Não, cancelar"))
        self.label_2.setText(_translate("TelaConfirmacao", "2022 CopyRight © Solutech"))
#import images_rc
